/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.7 Home.gltf --transform
Author: saeedakbari (https://sketchfab.com/saakbary64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-luxury-villa-house-building-d8e6be2601474f7d8cb7d06f8566f01a
Title: Modern luxury villa house building
*/

import { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

export default function HomeModel(props) {
  const { nodes, materials } = useGLTF("/Home-transformed.glb");

  const group = useRef();

  // useFrame(() => {
  //   if (t1.current) {
  //     t1.current.seek(scroll.offset * t1.current.duration());
  //   }
  // });

  useLayoutEffect(() => {
    const ctx = gsap.context(() => {
      const t1 = gsap.timeline();
      gsap.to(group.current.rotation, {
        y: Math.PI / 3,

        scrollTrigger: {
          trigger: ".second",
          start: "top bottom",
          // end: " top top ",
          end: () => `+=${2000}vh`,
          scrub: 1,
        },
      });

      gsap.to(group.current.position, {
        y: 1.2,
        scrollTrigger: {
          trigger: ".second",
          start: "top bottom",
          // end: " top top ",
          end: () => `+=${2000}vh`,
          scrub: 1,
        },
      });
    });

    // t1.current = gsap.timeline();

    // t1.current.to(
    //   group.current.rotation,
    //   {
    //     duration: 1,
    //     y: Math.PI / 3,
    //   },
    //   0
    // );
    // t1.current.to(
    //   group.current.position,
    //   {
    //     duration: 1,
    //     y: 1.5,
    //   },
    //   0
    // );
    return () => {
      ctx.revert();
    };
  }, []);

  return (
    <group ref={group} {...props} position={[0, -1, -0]} dispose={null}>
      <group scale={0.003}>
        <group
          position={[-250.99, 495.54, 208.33]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["Shape002_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-378.72, 495.54, 208.99]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["Shape003_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-433.28, 495.54, -24.57]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape004_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-433.28, 155.47, 94.2]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape005_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-433.28, 155.47, -148.41]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape006_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-537.18, 155.47, -375.64]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape007_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-490.87, 495.54, -564.14]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape008_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-490.87, 495.54, -771.81]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape009_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-431.61, 175.52, -758.45]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape010_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-431.64, 175.41, -562.17]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape011_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-250.99, 175.44, 208.99]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["Shape012_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-6.55, 502.13, 322.22]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["Shape013_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[425.72, 502.13, 199.61]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape014_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[425.72, 181.46, 199.61]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape015_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[521.45, 502.13, -127.35]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape016_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[521.45, 182.15, -127.35]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape017_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[528.49, 182.15, -500.3]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape018_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[655.79, 502.13, -403.96]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            geometry={nodes["Shape019_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[391.66, 502.13, -845.35]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Shape020_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[387.48, 181.52, -845.35]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Shape021_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-56.43, 181.52, -956.4]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Shape022_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-80.53, 499.27, -1012.9]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Shape023_Material_#246_0"].geometry}
            material={materials.Material_246}
            position={[206.35, 436.17, -200.5]}
          />
        </group>
        <group
          position={[-495.05, 494.97, -570.05]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes["Box015_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <group
          position={[-490.84, 494.97, -857.15]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes["Box016_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <group
          position={[-433.75, 175.19, -563.18]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes["Box017_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <group
          position={[-433.73, 174.71, -841.74]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes["Box018_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <group
          position={[-100.16, 174.71, -958.07]}
          rotation={[Math.PI, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Box019_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <group
          position={[-100.16, 494.63, -1011.86]}
          rotation={[Math.PI, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Box020_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <group
          position={[343.39, 494.63, -846.73]}
          rotation={[Math.PI, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Box021_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <group
          position={[343.39, 175.6, -846.92]}
          rotation={[Math.PI, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes["Box022_Material_#6_0"].geometry}
            material={materials.Material_6}
            position={[-64.38, -320.03, -0.47]}
          />
        </group>
        <mesh
          geometry={nodes["Line014_Material_#248_0"].geometry}
          material={materials.Line016__0}
          position={[-26.04, 320.01, -223.46]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line015_Material_#250_0"].geometry}
          material={materials.Material_250}
          position={[-26.04, 640.41, -223.46]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Line016__0.geometry}
          material={materials.Line016__0}
          position={[-26.04, 0.13, -223.46]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line009_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[410.78, 318.68, 298.71]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line013_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-403.68, 318.68, -169.6]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line010_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[338.95, 318.68, -322.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line011_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[367.28, 318.68, -722.7]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line012_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-194.33, 318.68, -662.3]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line017_Material_#253_0"].geometry}
          material={materials.Material_253}
          position={[-61.2, 513.34, -327.91]}
        />
        <mesh
          geometry={nodes["Box001_Material_#253_0"].geometry}
          material={materials.Material_253}
          position={[-241.19, 575.39, 201.37]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box002_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-138.99, 552.42, 306.82]}
        />
        <mesh
          geometry={nodes["Line018_Material_#248_0"].geometry}
          material={materials.Line016__0}
          position={[-26.04, 25.06, -223.46]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box003_Material_#12_0"].geometry}
          material={materials.Material_12}
          position={[58.7, 0, 393.95]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line019_Material_#252_0"].geometry}
          material={materials.Material_252}
          position={[13.19, 55.15, 340.96]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line020_Material_#252_0"].geometry}
          material={materials.Material_252}
          position={[13.19, 36.73, 380.36]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line021_Material_#252_0"].geometry}
          material={materials.Material_252}
          position={[13.19, 20.72, 380.36]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line022_Material_#252_0"].geometry}
          material={materials.Material_252}
          position={[13.19, 12.31, 380.36]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line002_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[379, 0, -696.03]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line003_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[461.14, 0, -107.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line006_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-18.24, 0, 214.68]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line007_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-400.78, 0, 160.51]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line008_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-287.63, 0, -186.7]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Rectangle001_wall_0.geometry}
          material={materials.Line016__0}
          position={[135.53, 0, -291.14]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line001_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-146.53, 0, -627.82]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line023_Material_#253_0"].geometry}
          material={materials.Material_253}
          position={[512.42, 425.23, -271.58]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box004_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[414.06, 0, 346.58]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box005_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[394.34, 0, 346.58]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box006_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[374.61, 0, 346.58]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box007_Material_#12_0"].geometry}
          material={materials.Material_12}
          position={[-278.58, 668.66, -365.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Shape001_Material_#246_0"].geometry}
          material={materials.Material_246}
          position={[461.14, 0, -94.88]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box008_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-251.01, 175.74, 208.57]}
        />
        <mesh
          geometry={nodes["Box009_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-442.5, 490.92, 204.1]}
        />
        <mesh
          geometry={nodes["Box010_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-306.97, 490.92, 204.1]}
        />
        <mesh
          geometry={nodes["Box011_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-431.68, 496.18, -94.19]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box012_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-430.16, 174.94, 22.62]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box013_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-430.16, 174.94, -219.41]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box014_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-533.94, 174.94, -434.65]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Line024_Material_#253_0"].geometry}
          material={materials.Material_253}
          position={[-414.51, 575.12, -972.99]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box023_Material_#242_0"].geometry}
          material={materials.Material_242}
          position={[-469.84, 0, 58.49]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box024_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-69.7, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box025_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-100.72, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box026_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-131.74, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box027_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-162.76, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box028_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-193.78, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box029_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-229.31, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box030_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-264.85, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box031_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-300.38, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box032_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-335.91, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box033_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-371.45, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box034_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-406.98, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box035_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-445.02, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box036_Material_#245_0"].geometry}
          material={materials.Material_245}
          position={[38.61, 171.58, 306.18]}
        />
        <mesh
          geometry={nodes["Box037_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[42.14, 200.72, 310.69]}
        />
        <mesh
          geometry={nodes["Sphere001_Material_#245_0"].geometry}
          material={materials.Material_245}
          position={[-20.2, 155.93, 319.51]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.32}
        />
        <mesh
          geometry={nodes["Cylinder001_Material_#243_0"].geometry}
          material={materials.Material_243}
          position={[-18.02, 155.93, 320.02]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={0.32}
        />
        <mesh
          geometry={nodes["Box038_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[507.27, 175.74, -405.9]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box039_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-354.78, 478.78, -117.61]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Shape024_Material_#2_0"].geometry}
          material={materials.Line016__0}
          position={[-483.06, 303.05, -407.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line025_Material_#246_0"].geometry}
          material={materials.Material_246}
          position={[82.09, 716.24, -217.6]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box040_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-485.47, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box041_Material_#244_0"].geometry}
          material={materials.Material_244}
          position={[-516.7, 662.3, -229.2]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Object001_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[338.95, 318.68, -322.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Object002_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[461.14, 0, -107.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder002_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-91.97, 0, 339.44]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder011_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-95.22, -23.46, 218.71]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder012_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-95.22, -23.46, 282.87]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder013_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-274.19, -23.46, 282.87]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder014_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-434.08, -23.46, 282.87]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder015_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-504.87, -23.46, 282.87]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder016_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-504.87, -23.46, 219.55]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder017_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-434.81, -23.46, 219.55]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder018_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-276.51, -23.46, 219.55]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder019_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-504.87, -23.46, -4.94]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder020_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-434.81, -23.46, -4.94]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder021_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-504.87, -23.46, -229.39]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder022_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-434.81, -23.46, -229.39]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder023_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-590.27, -23.46, -229.39]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder024_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-590.27, -23.46, -159.16]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder025_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-520.43, -23.46, -159.16]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder026_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-590.27, -23.46, -502.21]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder027_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-590.27, -23.46, -574.34]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder028_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-520.7, -23.46, -574.34]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder029_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-521, -23.46, -502.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder030_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-434.65, -23.46, -510.19]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder031_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-504.19, -23.46, -510.19]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder032_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-434.65, -23.46, -718.73]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder033_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-504.19, -23.46, -718.73]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder034_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-434.65, -23.46, -940.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder035_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-504.19, -23.46, -940.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Rectangle002_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-469.45, 39.99, -724.97]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Rectangle003_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-555.96, 39.99, -724.97]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Rectangle004_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-555.5, 39.99, -652.14]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Rectangle005_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-469.03, 39.99, -313.49]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Rectangle006_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-690.92, 39.99, 253.73]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes["Cylinder036_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-83.49, 345.65, 364.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder037_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-83.49, 345.65, 344.82]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder038_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-183.17, 345.65, 364.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder039_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-282.86, 345.65, 364.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder040_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-382.55, 345.65, 364.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder041_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-481.48, 345.65, 364.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder042_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-481.48, 345.65, 296.67]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder043_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-492.73, 345.65, 21.97]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder044_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-561.49, 345.65, 21.97]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder045_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-561.49, 345.65, -109.88]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder046_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-561.49, 345.65, -245.8]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder047_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-536.19, 345.65, -245.8]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line030_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-282.23, 411.24, 340.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder048_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-481.48, 345.65, 227.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line031_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-535.4, 410.77, -111.87]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder049_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[537.61, 363.16, -61.77]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder050_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[620.62, 363.16, -61.77]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder051_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[708.54, 363.16, -61.77]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder052_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[708.54, 363.16, -235.1]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder053_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[708.54, 363.16, -401.56]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder054_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[662.58, 363.16, -401.56]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line032_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[649.65, 428.25, -231.49]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder055_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-91.97, 0, 436.25]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder056_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-91.97, -17.09, 515.98]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder057_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-91.97, -35.01, 591]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder058_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-91.97, -49.04, 650.52]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line033_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-92.16, 117.99, 474.87]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Line034_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-92.16, 106.13, 474.87]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Line035_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-92.16, 94.27, 474.87]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Line036_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-92.16, 82.41, 474.87]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box042_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[127.35, 651.93, -366.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder059_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[131.79, 618.69, 343.9]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder060_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[131.79, 618.69, 301.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder061_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-183.13, 618.69, 301.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder062_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-183.13, 618.69, 199.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder063_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-472.93, 618.69, 199.01]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder064_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-472.93, 618.69, -14.3]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder065_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-472.93, 618.69, -227.61]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder066_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-482.59, 618.69, -502.7]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder067_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-482.59, 618.69, -735.45]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder068_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-482.59, 618.69, -1004.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder069_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-177.93, 618.69, -1004.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder070_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[116.46, 618.69, -1004.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder071_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[116.46, 618.69, -842.35]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder072_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[647.63, 618.69, -842.35]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder073_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[647.63, 618.69, -558.5]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder074_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[647.63, 618.69, -309.71]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder075_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[513.25, 618.69, -307.42]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder076_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[513.25, 618.69, -51.06]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Cylinder077_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[416.01, 618.69, -51.06]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.85}
        />
        <mesh
          geometry={nodes["Line037_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[123.52, 730.97, -197.3]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line038_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-481.69, 730.97, -742.27]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line039_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[123.52, 737.29, -197.3]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line040_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-481.69, 737.29, -742.27]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line041_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-282.23, 406.38, 340.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line042_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-535.4, 406.3, -111.87]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line043_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[649.65, 423.82, -231.49]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder078_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[539.47, 32.45, -341.47]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder079_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[617.62, 32.45, -341.47]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder080_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[706.71, 32.45, -341.47]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder081_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[706.71, 32.45, -496.34]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder082_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[706.71, 32.45, -645.53]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line044_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[646.08, 92.98, -447.97]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line045_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[646.08, 96.99, -447.97]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line047_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[52.11, 118.74, 311.13]}
        />
        <mesh
          geometry={nodes["Line048_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[52.11, 150.25, 311.13]}
        />
        <mesh
          geometry={nodes["Line050_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[52.11, 222.47, 311.13]}
        />
        <mesh
          geometry={nodes["Line051_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[52.11, 263.17, 311.13]}
        />
        <mesh
          geometry={nodes["Object003_Material_#15_0"].geometry}
          material={materials.Material_15}
          position={[-138.99, 552.42, 306.82]}
        />
        <mesh
          geometry={nodes["Box043_Material_#251_0"].geometry}
          material={materials.Material_251}
          position={[-305.46, 348.67, 282.27]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box044_Material_#251_0"].geometry}
          material={materials.Material_251}
          position={[-738.21, 348.67, -47.48]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box045_Material_#251_0"].geometry}
          material={materials.Material_251}
          position={[679.91, 348.67, -339.69]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box046_Material_#251_0"].geometry}
          material={materials.Material_251}
          position={[691.69, 52.37, -540.52]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box047_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-524.65, 285.78, -361.47]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes["Line052_Material_#246_0"].geometry}
          material={materials.Material_246}
          position={[-282.23, 402.81, 340.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line053_Material_#246_0"].geometry}
          material={materials.Material_246}
          position={[-527.9, 402.88, -116.96]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder083_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[83.02, 285.35, 350.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder084_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-6.76, 285.35, 350.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder085_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-108.97, 285.35, 350.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder086_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[83.02, 618.51, 376.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder087_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-6.76, 615.73, 376.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder088_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-108.97, 618.51, 376.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder089_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-256.57, 571.28, 237.68]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder090_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-381.47, 571.28, 237.68]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder091_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-526.86, 571.28, 237.68]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder092_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-526.86, 571.28, 123.56]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder093_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-526.86, 571.28, 9.44]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder094_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-487.29, 636.31, -41.71]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder095_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-487.29, 636.31, -186.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder096_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-526.59, 571.08, -570]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder097_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-526.59, 571.08, -827.17]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder098_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-469.53, 313.8, -814.34]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder099_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-469.53, 313.8, -560.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder100_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-141.82, 315.71, -977.83]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder101_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[60.99, 570.81, -1042.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder102_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-97.65, 570.81, -1042.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder103_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-224.33, 570.81, -1042.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder104_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-361.22, 570.81, -1042.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder105_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-526.19, 570.81, -1042.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder106_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-454.49, 315.71, -977.83]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder107_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.25, 578.8, -615.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder108_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.25, 578.8, -530.39]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder109_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.25, 578.8, -423.58]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder110_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.25, 578.8, -290.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder111_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[550.69, 578.8, -255.59]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder112_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[550.69, 578.8, -133.9]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder113_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[550.69, 578.8, -35]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder114_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.91, 578.8, -255.59]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder115_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.91, 578.8, -133.9]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder116_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.91, 578.8, -35]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder117_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[550.69, 315.63, -255.59]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder118_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[550.69, 315.63, -133.9]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder120_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.91, 315.63, -255.59]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder121_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[686.91, 315.63, -133.9]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder122_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[83.02, 285.35, 416.89]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder123_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-6.76, 285.35, 416.89]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder124_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-108.97, 285.35, 416.89]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder125_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-214.83, 618.51, 376.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder126_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-214.83, 618.51, 272.49]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder127_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-222.66, 315.19, 337.69]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder128_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-367.13, 315.19, 337.69]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder129_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-222.66, 315.19, 257.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder130_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-367.13, 315.19, 257.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder131_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-486.18, 315.19, -36.65]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder132_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-486.18, 315.19, -154.44]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder133_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-404.98, 636.31, -186.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line054_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-414.51, 789.64, -719.26]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder134_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-557.37, 785.66, -371.84]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder135_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-557.37, 785.66, -279]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder136_Material_#247_0"].geometry}
          material={materials.Material_247}
          position={[-557.37, 785.66, -460]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line055_Material_#4_0"].geometry}
          material={materials.Material_4}
          position={[72.69, 42.5, 615.17]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder157_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-335.65, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder158_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-425.08, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder159_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-514.51, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder160_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-603.94, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder161_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-693.37, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder162_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-860.63, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder163_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-955.66, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder164_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1050.7, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder165_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1145.73, 147.64, 1374.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder166_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 1279.21]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder167_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 1166.93]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder168_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 1054.66]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder169_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 942.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder170_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 821.8]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder171_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 696.92]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder172_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 572.05]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder173_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 367.97]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder174_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 277.16]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder175_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 186.34]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder176_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, 95.52]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder177_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -137.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder178_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -258.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder179_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -380.19]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder180_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -601.48]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder181_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -721.8]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder182_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -842.12]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder183_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -1071.33]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder184_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -1183.33]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder185_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -1295.32]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder186_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -1407.31]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder187_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1255.64, 147.64, -1548.04]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder188_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-1111.43, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder189_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-955.53, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder190_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-799.63, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder191_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-643.73, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder192_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-487.82, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder193_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-331.92, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder194_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-176.02, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder195_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[-20.12, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder196_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[135.79, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder197_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[291.69, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder198_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[416.74, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder199_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[541.8, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder200_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[666.85, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder201_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[791.9, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder202_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[916.95, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder203_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1042.01, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder204_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1182.92, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder205_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1323.82, 147.64, -1653]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder206_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -1562.11]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder207_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -1411.43]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder208_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -1260.76]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder209_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -1110.09]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder210_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -959.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder211_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -808.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder212_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -658.08]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder213_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -560.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder214_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -356.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder215_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -206.07]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder216_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -55.4]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder217_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 95.27]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder218_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 245.94]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder219_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 396.61]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder220_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 547.28]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder221_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 697.95]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder222_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 848.62]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder223_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 999.29]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder224_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 1149.96]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder225_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, 1300.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder226_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1329.18, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder227_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1401.46, 147.64, -463.27]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder228_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1201.25, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder229_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[1073.31, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder230_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[945.37, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder231_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[817.43, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder232_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[699.97, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder233_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[582.51, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Cylinder234_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[503.16, 147.64, 1374.15]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line057_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[76.77, 138.56, 364.82]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line058_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[76.77, 158.85, 364.82]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line059_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[76.77, 179.15, 364.82]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line060_Material_#249_0"].geometry}
          material={materials.Material_249}
          position={[76.77, 198.95, 364.82]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Line061_Material_#13_0"].geometry}
          material={materials.Material_13}
          position={[-78.93, 2.01, -106.43]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Rectangle007_Material_#11_0"].geometry}
          material={materials.Material_11}
          position={[73.13, 0, -139.81]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box048_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[483.47, 0, 1194.66]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box049_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[483.47, 0, 862.57]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box050_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[483.47, 0, 530.17]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box051_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[589.03, 0, 526.37]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box052_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[589.03, 0, 156.37]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box053_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[856.22, 0, 156.37]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box054_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[856.22, 0, -483.16]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box055_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[856.22, 0, -1028.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box056_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[341.79, 0, -1046.48]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box057_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-261.57, 0, -1291.16]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box058_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-863.6, 0, -1291.3]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box059_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-923.14, 0, -654.78]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box060_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-863.32, 0, -654.78]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box061_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-923.68, 0, -236]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box062_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-923.68, 0, 110.55]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box063_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-760.36, 0, 285.18]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box064_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-760.36, 0, 499.44]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box065_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-532.61, 0, 536.47]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box066_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-338.48, 0, 536.41]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box067_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-338.2, 0, 847.21]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box068_Material_#24_0"].geometry}
          material={materials.Material_24}
          position={[-338.53, 0, 1192.9]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box069_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[-4.8, 496.24, 326.97]}
        />
        <mesh
          geometry={nodes["Box070_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[208.44, 496.24, 342.56]}
        />
        <mesh
          geometry={nodes["Box071_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[425.96, 493.57, 226.32]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box072_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[425.96, 172.13, 220.54]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box073_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[525.69, 172.13, -113.25]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box074_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[525.69, 172.13, -503.16]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box075_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[651.83, 438.74, -390.53]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["Box076_Material_#6_0"].geometry}
          material={materials.Material_6}
          position={[524.65, 438.74, -112.23]}
          rotation={[0, Math.PI / 2, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Home-transformed.glb");
